#!/bin/bash
#Derived from script @ http://www.linuxjournal.com/content/temper-pi

TEMP_MIN="55"
TEMP_MAX="65"

LOGFILE='/var/log/temper.log'
TIME=`date +"%b %d %T"`
TEMPERATURE=`/usr/local/sbin/temper.py 2>/dev/null | 
 ↪tail -n1 | cut -f4 -d ' ' | sed 's/.F$//'`

if [[ $TEMPERATURE == "" ]]; then
  echo ERROR
  exit 1
fi

# B6 = peltier cooler B7 = heater

if [[ $TEMPERATURE < $TEMP_MIN ]]; then #too cold
echo -e "$TIME\t$TEMPERATURE\tCOLD" >> $LOGFILE
elif [[ $TEMPERATURE > $TEMP_MAX ]]; then #too hot
echo -e "$TIME\t$TEMPERATURE\tHOT" >> $LOGFILE
fi
echo -e "$TIME\t$TEMPERATURE\t" >> $LOGFILE
